services:
  web-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "trackrv2-web-api"
    ports:
      - "80:8080"
      - "443:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production # Change to Development when developing
      - ASPNETCORE_URLS=http://+:8080
      - JwtConfig__Key=${JWT_SECRET_KEY}
      - JwtConfig__Issuer=${JwtConfig__Issuer}
      - JwtConfig__Audience=${JwtConfig__Audience}
      - CONNECTION_STRING=${CONNECTION_STRING}
      - SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD}
      - DOTNET_RUNNING_IN_CONTAINER=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
